### ISSUE TITLE
Add .puz converter for coded crosswords

### ISSUE THREAD

**Issue by boisvert42** [jpd236/kotwords#21]
If someone makes a .puz with all the metadata, it should be straightforward to extract that and the grid to make a coded.

**Comment by jpd236** [comment]
See "Import PUZ" button at the bottom of https://jpd236.github.io/kotwords/coded.html.

Rather than treat it as a separate form (like we do for APZ/RGZ files), it felt better to me to treat it as a data source for imports which populates the form fields accordingly. This way, you can easily make tweaks to the resulting import (e.g. add a description) before generating the JPZ. You can also save the result as a .json data file and come back to it later if further edits are needed.

Let me know if there's anything else that would make this easier to use, and thanks for the suggestion!
